// SPDX-License-Identifier: MIT
pragma solidity ^0.8.33;

import {BaseTest} from "./BaseTest.sol";
import "forge-std/Test.sol";
import {LibHeapHarness} from "../contracts/test/LibHeapHarness.sol";

contract LibHeapGas is BaseTest {
    LibHeapHarness harness;

    function setUp() public override {
        super.setUp();
        harness = new LibHeapHarness();
    }

    // Benchmark-style test: create a large heap with many invalids and perform many pops
    // This will appear in the gas report generated by forge
    function test_gas_pop_with_many_invalids() public {
        uint256 labId = 200;
        uint256 n = 800; // > MAX_COMPACTION_SIZE to test both paths
        for (uint256 i = 0; i < n; i++) {
            bytes32 k = keccak256(abi.encodePacked("g", i));
            harness.enqueueViaLib(labId, k, uint32(1000 + i));
            if (i % 4 == 0) {
                harness.setReservation(k, labId, 5); // CANCELLED
            } else {
                harness.setReservation(k, labId, 1); // CONFIRMED
            }
        }
        harness.setInvalidCount(labId, n / 4);

        // perform up to 200 pops or until none available
        uint256 pops = 0;
        for (uint256 i = 0; i < 200; i++) {
            bytes32 p = harness.popEligible(labId, block.timestamp + 1 days);
            if (p == bytes32(0)) break;
            pops++;
        }

        // record checks to avoid optimization removal
        assertTrue(pops > 0, "no pops performed");
    }
}
